version: '2'
services:
  plex:
    restart: always
    image: "timhaak/plex"
    container_name: plex
    ports:
      - 32400:32400
    network_mode: host
    volumes:
      - ~/media:/data
      - plex_config:/config

  transmission:
    restart: always
    image: "dperson/transmission"
    container_name: transmission
    ports:
      - 9091:9091
    volumes:
      - ~/media:/var/lib/transmission-daemon/downloads

  sonarr:
    restart: always
    image: "linuxserver/sonarr"
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - ~/media:/volumes/media 
      - ~/media:/volumes/completed
      - sonarr_config:/config
      - sonarr_tv:/tv
    links:
      - transmission

volumes:
  plex_config: {}
  sonarr_config: {}
  sonarr_tv: {}
